### PR TITLE
add the image pull secret to kube-state-metrics

### PR DESCRIPTION
**Pull request by andreaTP**
Related to this support case:
https://support.lightbend.com/support/lightbend/ShowHomePage.do#Cases/dv/427921000018264001

### CODE REVIEW

**Comment by marcospereira** [comment]
`<scratching-my-head>`Why is CircleCI not building this pr?`</scratching-my-head>`

**Comment by marcospereira** [comment]
> `<scratching-my-head>`Why is CircleCI not building this pr?`</scratching-my-head>`

Meh, so Circle is configured NOT TO build forked pull request.

**Review by marcospereira — APPROVED** [review]
This LGTM, though. So let's merge and see how the build against master goes. :-)

**Comment by andreaTP** [comment]
thanks! 👍

**Comment by marcospereira** [comment]
@andreaTP should we release a new version?

**Comment by andreaTP** [comment]
Not a strict requirement, we will make a user happy if we do @marcospereira

**Comment by marcospereira** [comment]
@andreaTP see https://github.com/lightbend/console-charts/releases/tag/v1.2.16

**Pull request merged**
