### PR TITLE
Bump es-console-spa to 1.0.3

### PR DESCRIPTION
**Pull request by jsravn**
- Customer logo
- Other improvements

Related also to https://github.com/lightbend/console-backend/issues/621

### CODE REVIEW

**Comment by pcraddick** [comment]
Looks like we made a mistake on the frontend side — we're reading a field called 'logo' rather than 'customer' :|

**Comment by pcraddick** [comment]
> Looks like we made a mistake on the frontend side — we're reading a field called 'logo' rather than 'customer' :|

Actually, nm. The real problem is that we deviated from the design proposal in https://waffle.io/lightbend/console-frontend/cards/5c4b6318c050740486ca0f5d
when it came to the PR

The FE is expecting:

```
window.installedConfig = {
  'logo': 'ibm'
};
```

**Comment by pcraddick** [comment]
'Paper' trail:

https://github.com/lightbend/console-frontend/issues/522#issuecomment-468743333

**Comment by katsutoxin** [comment]
@jsravn   I merged the same change in #323    It requires your change to make frontend e2e test passed

**Comment by jsravn** [comment]
Thanks @katsutoxin.

**Pull request closed without merging**
