### PR TITLE
Migrate build to central park 2

### PR DESCRIPTION
**Pull request by cunei**
For https://github.com/lightbend/console-backend/issues/669

### CODE REVIEW

**Comment by cunei** [comment]
Bump. I need to shut down Central Park 1, now...

**Comment by jsravn** [comment]
I haven't had a chance to look at this yet - can you give us until Monday? Thanks.

**Comment by jsravn** [comment]
ping @cunei

**Comment by cunei** [comment]
Sure, no problems. It's just that it is rather expensive to keep two clusters up, and Derek was quite rightly expecting the cost to go back to the original levels.
I'll follow this issue to keep up to date.

**Comment by jsravn** [comment]
Ok @cunei, we're off of CP1 now.

**Pull request merged**
