### PR TITLE
Ui 1.2.5/paul

### PR DESCRIPTION
**Pull request by pcraddick**

### CODE REVIEW

**Comment by jsravn** [comment]
Looks like v1.2.5 doesn't exist yet?

**Comment by pcraddick** [comment]
> Looks like v1.2.5 doesn't exist yet?

Here's the release

https://github.com/lightbend/es-console-spa/releases

Is this lost in some no-man's-land of builds; switching from Travis to Circle?

**Comment by jsravn** [comment]
Hi @pcraddick it looks like `1.2.5` was released rather than `v1.2.5`.

**Comment by jsravn** [comment]
I released v1.2.5, when the build is done we can kick off this build again.

**Comment by pcraddick** [comment]
Thanks @jsravn !

**Pull request merged**
